ALTER TABLE public.alumnos
  ADD COLUMN IF NOT EXISTS peso NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS altura NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS lesiones TEXT,
  ADD COLUMN IF NOT EXISTS objetivo TEXT;
